/* SPDX-FileCopyrightText: © 2022 Decompollaborate */
/* SPDX-License-Identifier: MIT */

RABBITIZER_DEF_INSTR_ID(powerpc, , INVALID,     .operands={0}, .instrType=RABBITIZER_INSTR_TYPE_UNKNOWN, .architectureVersion=-1)

#include "instructions/instr_id/powerpc/powerpc_normal.inc"


RABBITIZER_DEF_INSTR_ID(powerpc, , USERDEF_00, .operands={0})
RABBITIZER_DEF_INSTR_ID(powerpc, , USERDEF_01, .operands={0})
RABBITIZER_DEF_INSTR_ID(powerpc, , USERDEF_02, .operands={0})
RABBITIZER_DEF_INSTR_ID(powerpc, , USERDEF_03, .operands={0})
RABBITIZER_DEF_INSTR_ID(powerpc, , USERDEF_04, .operands={0})
RABBITIZER_DEF_INSTR_ID(powerpc, , USERDEF_05, .operands={0})
RABBITIZER_DEF_INSTR_ID(powerpc, , USERDEF_06, .operands={0})
RABBITIZER_DEF_INSTR_ID(powerpc, , USERDEF_07, .operands={0})
RABBITIZER_DEF_INSTR_ID(powerpc, , USERDEF_08, .operands={0})
RABBITIZER_DEF_INSTR_ID(powerpc, , USERDEF_09, .operands={0})
RABBITIZER_DEF_INSTR_ID(powerpc, , USERDEF_10, .operands={0})
RABBITIZER_DEF_INSTR_ID(powerpc, , USERDEF_11, .operands={0})
RABBITIZER_DEF_INSTR_ID(powerpc, , USERDEF_12, .operands={0})
RABBITIZER_DEF_INSTR_ID(powerpc, , USERDEF_13, .operands={0})
RABBITIZER_DEF_INSTR_ID(powerpc, , USERDEF_14, .operands={0})
RABBITIZER_DEF_INSTR_ID(powerpc, , USERDEF_15, .operands={0})
RABBITIZER_DEF_INSTR_ID(powerpc, , USERDEF_16, .operands={0})
RABBITIZER_DEF_INSTR_ID(powerpc, , USERDEF_17, .operands={0})
RABBITIZER_DEF_INSTR_ID(powerpc, , USERDEF_18, .operands={0})
RABBITIZER_DEF_INSTR_ID(powerpc, , USERDEF_19, .operands={0})

RABBITIZER_DEF_INSTR_ID(powerpc, , MAX, .operands={0})
